-- Migration 002: Billing periods table
-- Monthly billing records per pad, auto-generated by cron on the 1st of each month

CREATE TABLE IF NOT EXISTS billing_periods (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  pad_id        INT NOT NULL,
  tenant_id     INT DEFAULT NULL,                    -- snapshot of tenant at billing time
  period_start  DATE NOT NULL,                       -- e.g. 2026-03-01
  period_end    DATE NOT NULL,                       -- e.g. 2026-03-31
  energy_kwh    DECIMAL(10,4) NOT NULL DEFAULT 0,
  rate_per_kwh  DECIMAL(10,4) NOT NULL,              -- rate snapshot at time of billing
  amount_due    DECIMAL(10,2) NOT NULL DEFAULT 0,    -- energy_kwh × rate_per_kwh
  status        ENUM('unpaid','paid','overdue','waived') NOT NULL DEFAULT 'unpaid',
  due_date      DATE NOT NULL,                       -- period_end + 7 days
  paid_at       DATETIME DEFAULT NULL,
  created_at    DATETIME NOT NULL DEFAULT NOW(),

  UNIQUE KEY uq_pad_period (pad_id, period_start),
  CONSTRAINT fk_bill_pad    FOREIGN KEY (pad_id)    REFERENCES pads(id)  ON DELETE CASCADE,
  CONSTRAINT fk_bill_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE SET NULL
);
