-- Migration 010: Billing periods table
-- Monthly billing records per pad, auto-generated by cron on the 1st of each month

CREATE TABLE IF NOT EXISTS billing_periods (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pad_id        INT UNSIGNED NOT NULL,
  tenant_id     INT UNSIGNED DEFAULT NULL,
  period_start  DATE NOT NULL,
  period_end    DATE NOT NULL,
  energy_kwh    DECIMAL(10,4) NOT NULL DEFAULT 0,
  rate_per_kwh  DECIMAL(10,4) NOT NULL,
  amount_due    DECIMAL(10,2) NOT NULL DEFAULT 0,
  status        ENUM('unpaid','paid','overdue','waived') NOT NULL DEFAULT 'unpaid',
  due_date      DATE NOT NULL,
  paid_at       DATETIME DEFAULT NULL,
  created_at    DATETIME NOT NULL DEFAULT NOW(),

  UNIQUE KEY uq_pad_period (pad_id, period_start),
  CONSTRAINT fk_bill_pad    FOREIGN KEY (pad_id)    REFERENCES pads(id)  ON DELETE CASCADE,
  CONSTRAINT fk_bill_tenant FOREIGN KEY (tenant_id) REFERENCES users(id) ON DELETE SET NULL
);
